skills_list=[
    "python",
    "java",
    "c++",
    "machine learning",
    "deep learning",
    "nlp",
    "tensorflow",
    "pytorch",
    "sql",
    "mysql",
    "power bi",
    " tableau",
    "excel",
    "flask",
    "django",
    "html",
    "css",
    "javascript",
    "react",
    "opencv",
    "data analysis",
    "aws",
    "docker",
    "kubernetes",
    "git",
    "linux",
     "mongodb",
    "pandas",
    "numpy",
    "scikit learn",
    "llms",
    "rag",
    "generative ai"
]